<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rhtml [
  <!ELEMENT rhtml (rhead,rscript*,rbody)>
  <!ELEMENT rhead (rmeta,rtitle?,rlink*)>
  <!ELEMENT rmeta (#PCDATA)>
  <!ELEMENT rtitle (#PCDATA)>
  <!ELEMENT rlink (#PCDATA)>
  <!ELEMENT rscript (#PCDATA)>
  <!ELEMENT rbody (ra*,rh1*,rh2*,rh3*,rh4*,rdiv*,rp*,rspan*,rul*,rimg*,rform)>
  <!ELEMENT ra (#PCDATA)>
  <!ELEMENT rh1 (#PCDATA)>
  <!ELEMENT rh2 (#PCDATA)>
  <!ELEMENT rh3 (#PCDATA)>
  <!ELEMENT rh4 (#PCDATA)>
  <!ELEMENT rdiv (#PCDATA)>
  <!ELEMENT rp (#PCDATA)>
  <!ELEMENT rspan (#PCDATA)>
  <!ELEMENT rul (rli*)>
  <!ELEMENT rli (#PCDATA)>
  <!ELEMENT rimg (#PCDATA)>
  <!ELEMENT rform (rlabel+,rinput+,rtextarea?,rbutton?)>
  <!ELEMENT rlabel (#PCDATA)>
  <!ELEMENT rinput (#PCDATA)>
  <!ELEMENT rbutton (#PCDATA)>
  <!ELEMENT rtextarea (#PCDATA)>
]>

<rhtml>

  <rhead>
    <rmeta></rmeta>
    <rtitle>PRUEBA</rtitle>
   <rlink></rlink>
   <rlink></rlink>
  </rhead>

  <rscript></rscript>

  <rbody>
    <ra></ra>
    <rh1></rh1>
    <rh2></rh2>
    <rh3></rh3>
    <rh4></rh4>
    <rdiv></rdiv>
    <rp></rp>
    <rspan></rspan>
    <rul>
      <rli></rli>
      <rli></rli>
      <rli></rli>
      <rli></rli>
    </rul>
    <rimg></rimg>
    <rform>
      <rlabel></rlabel>
      <rinput></rinput>
      <rtextarea></rtextarea>
      <rbutton></rbutton>
    </rform>
  </rbody>
</rhtml>